// <auto-generated />
namespace JobHunt.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Contact_company_lead_initial : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Contact_company_lead_initial));
        
        string IMigrationMetadata.Id
        {
            get { return "201508220333551_Contact_company_lead_initial"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
